delete unused functions, compile with different BUFFER_SIZE

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+make fclean
+
 BONUS=
 
 for i in $@
@@ -10,6 +12,7 @@ do
 	fi
 done
 
+printf "BUFF_SIZE = 42\n"
 make ${BONUS} BUFF_SIZE=42
 
 if [ $? -ne 0 ]
@@ -27,36 +30,38 @@ else
 	make fclean
 fi
 
-# make BUFF_SIZE=1
+printf "BUFF_SIZE = 1\n"
+make ${BONUS} BUFF_SIZE=1
 
-# if [ $? -ne 0 ]
-# then
-# 	echo -e "\033[1;31m\ncompilation error.\033[0;0m"
-# 	python3 output_sean.py
-# 	if [ $? -ne 0 ]
-# 	then
-# 		cat sean.txt
-# 	fi
-# 	exit 1
-# else
-# 	echo "./tester $@ 2>myleaks.txt"
-# 	./tester $@ 2>myleaks.txt
-# 	make fclean
-# fi
+if [ $? -ne 0 ]
+then
+	echo -e "\033[1;31m\ncompilation error.\033[0;0m"
+	python3 output_sean.py
+	if [ $? -ne 0 ]
+	then
+		cat sean.txt
+	fi
+	exit 1
+else
+	echo "./tester $@ 2>myleaks.txt"
+	./tester $@ 2>myleaks.txt
+	make fclean
+fi
 
-# make BUFF_SIZE=1000
+printf "BUFF_SIZE = 1000\n"
+make ${BONUS} BUFF_SIZE=1000
 
-# if [ $? -ne 0 ]
-# then
-# 	echo -e "\033[1;31m\ncompilation error.\033[0;0m"
-# 	python3 output_sean.py
-# 	if [ $? -ne 0 ]
-# 	then
-# 		cat sean.txt
-# 	fi
-# 	exit 1
-# else
-# 	echo "./tester $@ 2>myleaks.txt"
-# 	./tester $@ 2>myleaks.txt
-# 	make fclean
-# fi
+if [ $? -ne 0 ]
+then
+	echo -e "\033[1;31m\ncompilation error.\033[0;0m"
+	python3 output_sean.py
+	if [ $? -ne 0 ]
+	then
+		cat sean.txt
+	fi
+	exit 1
+else
+	echo "./tester $@ 2>myleaks.txt"
+	./tester $@ 2>myleaks.txt
+	make fclean
+fi
